from  datetime import date

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from dfdrl import db
from dfdrl.models import (Team, Vehicle, Season, Event, EventType,
                          ChampionsLeagueResult)


# engine = create_engine("sqlite:///site.db")
# Session = sessionmaker(bind=engine)
# session = Session()

data = [
    # Team
    Team(name="Damon", affiliate="Police"),
    Team(name="Felix", affiliate="Security"),
    Team(name="Ian", affiliate="Datsun"),
    Team(name="Benny", affiliate="Nissan"),
    Team(name="Peter", affiliate="Dinosaurs"),

    # Vehicle
    # Season 1: initial league vehicles
    Vehicle(name="Ford Fairlane Station Wagon", team_id=1, weight=36, first_season=1, event_appearances=10, champion=0, second=0, third=0),
    Vehicle(name="Honda City Turbo (Red)", team_id=1, weight=31, first_season=1, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Porsche Wagon", team_id=1, weight=34, first_season=1, event_appearances=34, champion=1, second=0, third=1),
    Vehicle(name="Park Ranger", team_id=1, weight=37, first_season=1, event_appearances=11, champion=0, second=0, third=0),
    Vehicle(name="Hot Wheels Stock Car", team_id=1, weight=36, first_season=1, event_appearances=12, champion=0, second=0, third=1),
    Vehicle(name="1965 Mustang", team_id=1, weight=37, first_season=1, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Toaster Van", team_id=1, weight=32, first_season=1, event_appearances=11, champion=0, second=0, third=0),
    Vehicle(name="Ice Cream Van", team_id=1, weight=36, first_season=1, event_appearances=18, champion=0, second=0, third=0),
    Vehicle(name="Roller Coaster Car", team_id=1, first_season=1, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Koopa Troopa", team_id=1, weight=30, first_season=1, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Tesla Model 3", team_id=3, weight=35, first_season=1, event_appearances=10, champion=0, second=0, third=0),
    Vehicle(name="Fiat 500x", team_id=3, weight=30, first_season=1, event_appearances=10, champion=0, second=0, third=0),
    Vehicle(name="Honda City Turbo (Silver)", team_id=3, weight=30, first_season=1, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Garbage Truck", team_id=3, weight=37, first_season=1, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Flatbed Tow Truck", team_id=3, weight=37, first_season=1, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Porsche 944", team_id=3, weight=34, first_season=1, event_appearances=60, champion=0, second=1, third=0),
    Vehicle(name="1992 Mustang", team_id=3, weight=44, first_season=1, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Bumper Car", team_id=3, weight=26, first_season=1, event_appearances=26, champion=0, second=0, third=0),
    Vehicle(name="Michelangelo", team_id=3, first_season=1, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Cruise Bruiser", team_id=3, first_season=1, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Boone County Sheriff", team_id=4, weight=32, first_season=1, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Pacifica", team_id=4, first_season=1, weight=34, event_appearances=10, champion=0, second=0, third=0),
    Vehicle(name="Ford Escort Rally", team_id=4, weight=37, first_season=1, event_appearances=13, champion=0, second=0, third=0),
    Vehicle(name="Porsche Cayman", team_id=4, weight=31, first_season=1, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Blue Mazda", team_id=4, weight=34, first_season=1, event_appearances=27, champion=0, second=0, third=0),
    Vehicle(name="Yellow Porsche", team_id=4, weight=33, first_season=1, event_appearances=14, champion=0, second=0, third=0),
    Vehicle(name="Beetle Camper", team_id=4, weight=36, first_season=1, event_appearances=14, champion=0, second=0, third=0),
    Vehicle(name="Human Cannonball Car", team_id=4, weight=29, first_season=1, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Rockin' Santa", team_id=4, first_season=1, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Kick Kart", team_id=4, weight=43, first_season=1, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="Mercedes Benz Racer", team_id=5, weight=32, first_season=1, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Volvo 850 Station Wagon", team_id=5, weight=30, first_season=1, event_appearances=11, champion=0, second=0, third=0),
    Vehicle(name="King/Ace of Hearts Van", team_id=5, weight=46, first_season=1, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Chevy Camaro Convertible", team_id=5, weight=37, first_season=1, event_appearances=10, champion=0, second=0, third=0),
    Vehicle(name="Jaguar XJ220", team_id=5, weight=40, first_season=1, event_appearances=26, champion=0, second=0, third=1),
    Vehicle(name="Volkswagen SP2", team_id=5, weight=32, first_season=1, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Pedal Driver", team_id=5, weight=30, first_season=1, event_appearances=15, champion=0, second=0, third=0),
    Vehicle(name="Ninja Turtles Bus", team_id=5, weight=48, first_season=1, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Cool One", team_id=5, weight=41, first_season=1, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Aero Pod", team_id=5, weight=43, first_season=1, event_appearances=4, champion=0, second=0, third=0),
    # Season 2: new vehicles
    Vehicle(name="1968 Nova", team_id=1, weight=38, first_season=2, event_appearances=10, champion=0, second=0, third=0),
    Vehicle(name="Kia Stinger", team_id=1, weight=39, first_season=2, event_appearances=29, champion=2, second=1, third=0),
    Vehicle(name="2019 Benz", team_id=1, weight=33, first_season=2, event_appearances=10, champion=0, second=1, third=0),
    Vehicle(name="Forest Fire Truck", team_id=1, weight=27, first_season=2, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Tootsie Pop Van", team_id=1, weight=38, first_season=2, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="Jeepster", team_id=1, weight=38, first_season=2, event_appearances=6, champion=1, second=0, third=0),
    Vehicle(name="Ford GT40", team_id=1, weight=36, first_season=2, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Raphael", team_id=1, weight=41, first_season=2, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="Datsun Wagon", team_id=3, weight=34, first_season=2, event_appearances=15, champion=0, second=0, third=0),
    Vehicle(name="Ford Torino", team_id=3, weight=37, first_season=2, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Land Rover Park Ranger", team_id=3, weight=44, first_season=2, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Corvette", team_id=3, weight=34, first_season=2, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Acura Integra", team_id=3, weight=32, first_season=2, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="Velociracer", team_id=3, first_season=2, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Tokyo 2020", team_id=3, weight=32, first_season=2, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="Oscar Mayer Wienermobile (Silver)", team_id=3, weight=36, first_season=2, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="The Homer", team_id=3, weight=37, first_season=2, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Speed Driver", team_id=3, weight=39, first_season=2, event_appearances=12, champion=0, second=0, third=0),
    Vehicle(name="Flame Wagon", team_id=4, weight=37, first_season=2, event_appearances=11, champion=0, second=0, third=0),
    Vehicle(name="Ketchup Mustard", team_id=4, weight=34, first_season=2, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Nissan Titan", team_id=4, weight=45, first_season=2, event_appearances=33, champion=0, second=1, third=0),
    Vehicle(name="Recycle Truck", team_id=4, weight=36, first_season=2, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="Coors Truck", team_id=4, weight=32, first_season=2, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Portland Racer", team_id=4, weight=40, first_season=2, event_appearances=29, champion=0, second=0, third=0),
    Vehicle(name="Oscar Mayer Wienermobile", team_id=4, weight=36, first_season=2, event_appearances=18, champion=0, second=0, third=0),
    Vehicle(name="Surf 'n Turf ", team_id=4, weight=34, first_season=2, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Sky Boat", team_id=4, weight=33, first_season=2, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="1984 Audi Sport", team_id=5, weight=37, first_season=2, event_appearances=11, champion=0, second=0, third=0),
    Vehicle(name="Ford Maverick", team_id=5, weight=38, first_season=2, event_appearances=26, champion=0, second=0, third=0),
    Vehicle(name="Agave Van", team_id=5, weight=37, first_season=2, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="RoboRacer", team_id=5, weight=28, first_season=2, event_appearances=18, champion=0, second=0, third=1),
    Vehicle(name="Super Mario", team_id=5, weight=39, first_season=2, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Rip Rod", team_id=5, weight=30, first_season=2, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Cloak and Dagger", team_id=5, weight=29, first_season=2, event_appearances=4, champion=0, second=0, third=0),
    # Season 3: new vehicles
    Vehicle(name="Polizei", team_id=1, weight=40, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Hudson Hornet Police", team_id=1, weight=36, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Milk Truck", team_id=1, weight=50, first_season=3, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Baja Truck", team_id=1, weight=39, first_season=3, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Diaper Dragger", team_id=1, weight=28, first_season=3, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Rain Maker", team_id=1, weight=39, first_season=3, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Ford Maverick (Black)", team_id=3, weight=38, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Tootsie Roll Hummer", team_id=3, weight=35, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Jeep Wagoneer", team_id=3, weight=38, first_season=3, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Black Porsche", team_id=3, weight=33, first_season=3, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Poophead", team_id=3, weight=47, first_season=3, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="8 Crate", team_id=3, weight=42, first_season=3, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Honda Prelude", team_id=4, weight=35, first_season=3, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="No Name", team_id=4, weight=31, first_season=3, event_appearances=14, champion=0, second=0, third=0),
    Vehicle(name="Shelby Cobra", team_id=4, weight=32, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Tractor King", team_id=4, weight=28, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Fleetwood Mac", team_id=4, weight=30, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="The Queen", team_id=5, weight=48, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Mini Cooper", team_id=5, weight=42, first_season=3, event_appearances=10, champion=0, second=0, third=0),
    Vehicle(name="Porsche Wagon (White)", team_id=5, weight=35, first_season=3, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Cargo Courier", team_id=5, weight=37, first_season=3, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="Clip Rod", team_id=5, weight=32, first_season=3, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Bone Shaker", team_id=5, weight=25, first_season=3, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Baja Bug", team_id=5, weight=24, first_season=3, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Manga Tuner", team_id=5, weight=31, first_season=3, event_appearances=6, champion=0, second=0, third=0),
    # Season 4: new vehicles
    Vehicle(name="MGB Coupe", team_id=1, weight=35, first_season=4, event_appearances=13, champion=0, second=1, third=0),
    Vehicle(name="BMW Z4M", team_id=1, weight=36, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Big-Air Bel-Air", team_id=1, weight=34, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1986 Monte Carlo", team_id=1, weight=35, first_season=4, event_appearances=21, champion=1, second=1, third=0),
    Vehicle(name="Willys Jeepster", team_id=1, weight=27, first_season=4, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Quick Bite", team_id=1, weight=42, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Nissan Police", team_id=1, weight=38, first_season=4, event_appearances=22, champion=1, second=0, third=0),
    Vehicle(name="Duck 'n Roll", team_id=1, weight=30, first_season=4, event_appearances=11, champion=0, second=0, third=0),
    Vehicle(name="Pixel Shaker", team_id=1, weight=30, first_season=4, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="The Thing", team_id=3, weight=29, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1957 Plymouth Fury", team_id=3, weight=44, first_season=4, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Datsun Pickup", team_id=3, weight=34, first_season=4, event_appearances=21, champion=0, second=1, third=0),
    Vehicle(name="Armored Truck", team_id=3, weight=34, first_season=4, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Red Mazda", team_id=3, weight=35, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Gazella", team_id=3, weight=33, first_season=4, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Donut Drifter", team_id=3, weight=31, first_season=4, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Batmobile", team_id=3, weight=37, first_season=4, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="Aisle Driver", team_id=3, weight=35, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Lamborghini Urus", team_id=4, weight=36, first_season=4, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="NASA Support", team_id=4, weight=37, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Poop King", team_id=4, weight=43, first_season=4, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Mazda Miata", team_id=4, weight=34, first_season=4, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Toyota 2000 GT", team_id=4, weight=34, first_season=4, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Aston Martin One-77", team_id=4, weight=30, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Argyle Mazda", team_id=4, weight=35, first_season=4, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Hi-Tech Missile", team_id=4, weight=31, first_season=4, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Croc Rod", team_id=4, weight=34, first_season=4, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="1969 Dodge Charger 500", team_id=5, weight=41, first_season=4, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Ford Mustang Boss", team_id=5, weight=36, first_season=4, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1971 Dodge Charger", team_id=5, weight=38, first_season=4, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="1967 Camaro", team_id=5, weight=30, first_season=4, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Taffy King", team_id=5, weight=30, first_season=4, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Jaguar XE SV Project 8", team_id=5, weight=38, first_season=4, event_appearances=12, champion=0, second=0, third=0),
    Vehicle(name="Chevy Impala Stock Car", team_id=5, weight=35, first_season=4, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Sky Dome", team_id=5, weight=34, first_season=4, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Party Wagon", team_id=5, weight=38, first_season=4, event_appearances=6, champion=0, second=0, third=0),
    # Season 5: new vehicles
    Vehicle(name="Hudson Hornet Racer", team_id=1, weight=32, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Volkswagen Golf Polizei", team_id=1, weight=33, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1968 Dodge Dart", team_id=1, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Powell Pickup", team_id=1, weight=35, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Jurassic Park Jeep", team_id=1, weight=29, first_season=5, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1990 Acura NSX", team_id=1, weight=30, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Pete", team_id=1, weight=30, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Paradigm Shift", team_id=1, weight=35, first_season=5, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Fast Gassin'", team_id=1, weight=35, first_season=5, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="The Dragon", team_id=1, weight=31, first_season=5, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1965 Mustang Convertible", team_id=3, weight=31, first_season=5, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Pontiac Firebird", team_id=3, weight=32, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Toyota Prius", team_id=3, weight=39, first_season=5, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1969 Chevy Pickup", team_id=3, weight=31, first_season=5, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1964 Corvette Sting Ray", team_id=3, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Carbonator", team_id=3, weight=37, first_season=5, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Road Bandit Taxi", team_id=3, weight=38, first_season=5, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Donald Duck", team_id=3, weight=29, first_season=5, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Big Banana Car", team_id=3, weight=31, first_season=5, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Dream Mobile", team_id=3, weight=27, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1956 Aston Martin", team_id=4, weight=36, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Blue Volvo", team_id=4, weight=29, first_season=5, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Crown Victoria Taxi", team_id=4, weight=35, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Land Rover Defender", team_id=4, weight=39, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Nissan Van", team_id=4, weight=40, first_season=5, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Honda S2000", team_id=4, first_season=5, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Buns of Steel", team_id=4, weight=35, first_season=5, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Turbo Rooster", team_id=4, weight=33, first_season=5, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Pluto", team_id=4, weight=30, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Smiley Face", team_id=4, weight=32, first_season=5, event_appearances=8, champion=0, second=0, third=1),
    Vehicle(name="Honda Civic", team_id=5, weight=36, first_season=5, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1962 Volkswagen Beetle", team_id=5, weight=36, first_season=5, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="1970 Chevy Chevelle", team_id=5, weight=41, first_season=5, event_appearances=15, champion=1, second=0, third=0),
    Vehicle(name="Baja Blazer Land Rover", team_id=5, weight=33, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1952 Chevy Pickup", team_id=5, weight=38, first_season=5, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Indy Car", team_id=5, weight=30, first_season=5, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1971 Porsche 914", team_id=5, weight=26, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="2 Jet Z", team_id=5, weight=30, first_season=5, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Chip 'n Dale", team_id=5, weight=33, first_season=5, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Growler", team_id=5, weight=29, first_season=5, event_appearances=2, champion=0, second=0, third=0),
    # Season 6: new vehicles
    Vehicle(name="1969 Camaro Convertible", team_id=1, weight=34, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="National Parks Police", team_id=1, weight=37, first_season=6, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1962 Plymouth Savoy", team_id=1, weight=35, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Self-Driving Bus", team_id=1, weight=23, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Volkswagen Caddy", team_id=1, weight=34, first_season=6, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="2016 Lamborghini Centario Roadster", team_id=1, weight=29, first_season=6, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="Rigor Motor", team_id=1, weight=28, first_season=6, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Loopster", team_id=1, weight=30, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1964 Chevy Chevelle", team_id=3, weight=37, first_season=6, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1970 Datsun Rally", team_id=3, weight=39, first_season=6, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="1980 Mercedes Benz W123 Wagon", team_id=3, weight=35, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Mr. Bean", team_id=3, weight=29, first_season=6, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="1976 Honda CVCC", team_id=3, weight=31, first_season=6, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="1999 Ford F150 SVT Lightning", team_id=3, weight=38, first_season=6, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Street Wiener", team_id=3, weight=31, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Zombot", team_id=3, weight=33, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1996 Chevy Impala", team_id=4, weight=34, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Nissan Silvia", team_id=4, weight=34, first_season=6, event_appearances=8, champion=0, second=1, third=0),
    Vehicle(name="Ford Thunderbird", team_id=4, weight=32, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1949 Ford F1", team_id=4, weight=36, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Big Firetruck", team_id=4, weight=42, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1961 Ford Ranchero", team_id=4, weight=28, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Corvette Grand Sport Roadster", team_id=4, weight=36, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Barbie Dream Camper", team_id=4, weight=31, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1957 Chevy", team_id=5, weight=39, first_season=6, event_appearances=8, champion=0, second=0, third=1),
    Vehicle(name="2004 Audi RS6 Avant", team_id=5, weight=42, first_season=6, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Ford Capri", team_id=5, weight=35, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1991 GMC Syclone", team_id=5, weight=36, first_season=6, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1980 El Camino", team_id=5, weight=37, first_season=6, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Jack/Ace of Hearts Van", team_id=5, weight=40, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1956 Jaguar XK140 Roadster", team_id=5, weight=29, first_season=6, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Tanknator", team_id=5, weight=39, first_season=6, event_appearances=1, champion=0, second=0, third=0),
    # Season 7: new vehicles
    Vehicle(name="Mazda RX-3", team_id=1, weight=33, first_season=7, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="1957 T-Bird", team_id=1, weight=32, first_season=7, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="1949 Merc", team_id=1, weight=36, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Mercedes Benz 500 E", team_id=1, weight=39, first_season=7, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="DIVCO Milk Truck", team_id=1, weight=44, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="2009 International eStar", team_id=1, first_season=7, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1965 Land Rover GEN II Safari", team_id=1, weight=39, first_season=7, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="2020 Koenigsegg Jesko", team_id=1, weight=35, first_season=7, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Orange Miata", team_id=1, weight=33, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Mystery Machine", team_id=1, weight=50, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Head Gasket", team_id=1, weight=30, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Minecart", team_id=1, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Tanooki Mario", team_id=1, weight=36, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Lancia Delta Integrale", team_id=3, weight=40, first_season=7, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="1971 Datsun Bluebird 510", team_id=3, weight=37, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Bentley Bentayga", team_id=3, weight=39, first_season=7, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="1965 Ford Galaxie", team_id=3, weight=42, first_season=7, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Honda Civic Si", team_id=3, weight=40, first_season=7, event_appearances=25, champion=1, second=0, third=1),
    Vehicle(name="1949 Volkswagen Beetle Pickup", team_id=3, weight=37, first_season=7, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Subaru Sambar", team_id=3, first_season=7, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="2008 Holden Ute SSV", team_id=3, weight=36, first_season=7, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="2015 Mazda MX-5 Miata", team_id=3, weight=31, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Hot Tub", team_id=3, weight=35, first_season=7, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="Steer Clear", team_id=3, weight=33, first_season=7, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Emoticar", team_id=3, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Raijin Express", team_id=3, weight=42, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1985 Honda CRX", team_id=4, weight=35, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1982 Nissan Skyline RSX", team_id=4, weight=31, first_season=7, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="1971 Dodge Demon", team_id=4, weight=35, first_season=7, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="1994 Audi Avant RS2", team_id=4, weight=37, first_season=7, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="1995 Nissan Hardbody", team_id=4, weight=32, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1957 Dodge Sweptside", team_id=4, weight=40, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Road Stripe King", team_id=4, weight=39, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Nissan Fairlady Z", team_id=4, weight=34, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Porsche 911 Carrera Cabriolet", team_id=4, weight=36, first_season=7, event_appearances=8, champion=0, second=0, third=1),
    Vehicle(name="Car-de-Asada", team_id=4, weight=29, first_season=7, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Tooned Twinmill", team_id=4, weight=32, first_season=7, event_appearances=7, champion=0, second=1, third=0),
    Vehicle(name="Lego Car", team_id=4, first_season=7, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Hello Kitty Kool Kombi", team_id=4, weight=41, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Subaru WRX STI", team_id=5, weight=33, first_season=7, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="2018 Ford Mustang Convertible", team_id=5, weight=30, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Custom '69 Volkswagen Squareback", team_id=5, weight=34, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1973 Ford Falcon XB", team_id=5, weight=38, first_season=7, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1998 Subaru Impreza 228 STi-Version", team_id=5, weight=36, first_season=7, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Custom '72 Chevy Luv", team_id=5, weight=34, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="2016 Chevy Colorado Extreme", team_id=5, weight=34, first_season=7, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Ain't Fare", team_id=5, weight=38, first_season=7, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1995 Mazda RX-7", team_id=5, weight=36, first_season=7, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="2015 Jaguar F-TYPE Coupe", team_id=5, weight=35, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Tricera-Truck", team_id=5, weight=35, first_season=7, event_appearances=14, champion=0, second=0, third=0),
    Vehicle(name="Erikenstein Rod", team_id=5, weight=36, first_season=7, event_appearances=15, champion=0, second=0, third=0),
    Vehicle(name="Yellow Submarine", team_id=5, weight=35, first_season=7, event_appearances=2, champion=0, second=0, third=0),
    # Season 8: new vehicles
    Vehicle(name="1970 Chevy Camaro", team_id=1, weight=33, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Pictionary Camaro", team_id=1, weight=37, first_season=8, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="2010 Cadillac Wagon", team_id=1, weight=36, first_season=8, event_appearances=11, champion=0, second=0, third=0),
    Vehicle(name="1970 Toyota Celica", team_id=1, weight=31, first_season=8, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="1965 Mustang GT", team_id=1, weight=32, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Mini Cooper S Challenge", team_id=1, weight=30, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1975 Chevy Caprice", team_id=1, weight=33, first_season=8, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1982 Dodge Rampage", team_id=1, weight=39, first_season=8, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="1935 Ford Pickup", team_id=1, weight=31, first_season=8, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Ford GT-40 (White)", team_id=1, weight=34, first_season=8, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="2016 Ford GT Race", team_id=1, weight=32, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="McLaren Speedtail", team_id=1, weight=31, first_season=8, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Duck 'n Roll (Glow-in-the-Dark)", team_id=1, weight=31, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1968 Shelby GT 500", team_id=3, weight=35, first_season=8, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="1967 Shelby GT 500", team_id=3, weight=37, first_season=8, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Mustang Funny Car", team_id=3, weight=37, first_season=8, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1955 Cadillac Fleetwood", team_id=3, weight=37, first_season=8, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="1959 Chevy Wagon", team_id=3, weight=33, first_season=8, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="Custom '70 Honda N600", team_id=3, weight=33, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1968 Mustang GT CS", team_id=3, weight=36, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1976 Honda CVCC (White)", team_id=3, weight=31, first_season=8, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Dodge Van", team_id=3, weight=39, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Porsche 944 (Blue)", team_id=3, weight=33, first_season=8, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Porsche 993 GT2", team_id=3, weight=36, first_season=8, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Porsche 911 GT3 RS", team_id=3, weight=35, first_season=8, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Donut Drifter (Blueberry)", team_id=3, weight=31, first_season=8, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="1998 Honda Prelude", team_id=4, weight=36, first_season=8, event_appearances=22, champion=0, second=1, third=0),
    Vehicle(name="Nissan Skyline 2000 GT-R", team_id=4, weight=38, first_season=8, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="1977 Pontiac Firebird T-A", team_id=4, weight=35, first_season=8, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Custom Volkswagen Beetle", team_id=4, weight=27, first_season=8, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1941 Cadillac Series 62 Convertible Coupe", team_id=4, weight=30, first_season=8, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1971 Oldsmobile Vista Cruiser", team_id=4, weight=39, first_season=8, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="1979 Chevy Nova", team_id=4, weight=35, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Volkswagen Beetle", team_id=4, weight=30, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="2003 Nissan 350Z", team_id=4, weight=33, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="2018 Bugatti Divo", team_id=4, weight=34, first_season=8, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Dodge Viper RT/10", team_id=4, weight=35, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1963 Austin Healey 3000 MK2", team_id=4, weight=27, first_season=8, event_appearances=24, champion=1, second=0, third=0),
    Vehicle(name="Car-de-Asada (Red)", team_id=4, weight=29, first_season=8, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1969 Copo Camaro", team_id=5, weight=39, first_season=8, event_appearances=13, champion=0, second=0, third=0),
    Vehicle(name="1985 Chevrolet Camaro IROC-Z", team_id=5, weight=32, first_season=8, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Guster '55 Chevy Bel Air Gasser", team_id=5, weight=36, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1933 Plymouth Sedan", team_id=5, weight=34, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="2004 Audi RS6 Avant (Gray)", team_id=5, weight=41, first_season=8, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="2017 Honda Civic Hatchback", team_id=5, weight=32, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1971 Plymouth HEMI 'Cuda", team_id=5, weight=37, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="2019 Ford Mustang Coupe", team_id=5, weight=35, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Cadillac One", team_id=5, weight=36, first_season=8, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Jaguar XE SV Project 8 (Glittery Green)", team_id=5, weight=36, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Lamborghini Sesto Elemento", team_id=5, weight=37, first_season=8, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Mercedes-Benz 300 SL", team_id=5, weight=26, first_season=8, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Motosaurus", team_id=5, weight=32, first_season=8, event_appearances=8, champion=0, second=0, third=0),
    # Season 9: new vehicles
    Vehicle(name="1987 Buick Regal GNX", team_id=1, weight=38, first_season=9, event_appearances=8, champion=0, second=0, third=1),
    Vehicle(name="1969 BMW 2002", team_id=1, weight=32, first_season=9, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="1987 Ford Sierra Cosworth", team_id=1, weight=36, first_season=9, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="1971 Plymouth Road Runner", team_id=1, weight=38, first_season=9, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="1987 Dodge D100", team_id=1, weight=40, first_season=9, event_appearances=0, champion=0, second=0, third=0),
    Vehicle(name="1970 Chevy El Camino", team_id=1, weight=39, first_season=9, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="2021 Ford Bronco", team_id=1, weight=41, first_season=9, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="Lamborghini Countach Police Car", team_id=1, weight=37, first_season=9, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="McLaren F1", team_id=1, weight=34, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Standard Kart", team_id=1, weight=34, first_season=9, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Turtoshell", team_id=1, weight=29, first_season=9, event_appearances=8, champion=0, second=0, third=0),
    Vehicle(name="Rocket Box", team_id=1, weight=28, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1967 Pontiac GTO", team_id=3, weight=32, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1968 Citroën DS", team_id=3, weight=29, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Toyota AE86 Sprinter Trueno", team_id=3, weight=36, first_season=9, event_appearances=11, champion=0, second=0, third=0),
    Vehicle(name="1973 BMW Race Car", team_id=3, weight=33, first_season=9, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1967 Chevelle SS 396", team_id=3, weight=39, first_season=9, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1949 Volkswagen Beetle Pickup (Gray)", team_id=3, weight=36, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="2008 Holden UTE (White)", team_id=3, weight=36, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Pagani Huayra", team_id=3, weight=32, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Deora III", team_id=3, weight=36, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Crop Master", team_id=3, weight=31, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Tooligan", team_id=3, weight=34, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1970 Plymouth Barracuda", team_id=4, weight=34, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Christmas Ford Escort", team_id=4, weight=35, first_season=9, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1968 Mercury Cougar", team_id=4, weight=34, first_season=9, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="1962 Nissan Junior", team_id=4, weight=27, first_season=9, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1995 Nissan Hardbody (Black)", team_id=4, weight=32, first_season=9, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Porsche 356 Outlaw", team_id=4, weight=30, first_season=9, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="LB-Silhouette Works Nissan", team_id=4, weight=36, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="The Dark Knight Batmobile", team_id=4, weight=37, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Mad Splash", team_id=4, weight=29, first_season=9, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Bubble Matic", team_id=4, weight=37, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Street Cleaver", team_id=4, weight=35, first_season=9, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1967 Oldsmobile 442", team_id=5, weight=38, first_season=9, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Bureau de Poste Van", team_id=5, weight=35, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Mazda REPU", team_id=5, weight=35, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1967 Chevy C10", team_id=5, weight=38, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1955 Corvette", team_id=5, weight=46, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1984 Toyota MR2", team_id=5, weight=32, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="2020 Toyota GR Supra", team_id=5, weight=29, first_season=9, event_appearances=13, champion=0, second=0, third=0),
    Vehicle(name="McLaren F1 GTR", team_id=5, weight=36, first_season=9, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Baja Bone Shaker", team_id=5, weight=37, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Chill Mill", team_id=5, weight=37, first_season=9, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Sweet Driver", team_id=5, weight=28, first_season=9, event_appearances=1, champion=0, second=0, third=0),
    # Season 10: new vehicles
    Vehicle(name="Quick Bite (Hot Dog)", team_id=1, weight=41, first_season=10, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="1967 Jeepster Commando", team_id=1, weight=36, first_season=10, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1983 Chevy Silverado", team_id=1, weight=48, first_season=10, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="Olds 442", team_id=1, weight=37, first_season=10, event_appearances=5, champion=0, second=0, third=0),
    Vehicle(name="Tesla Roadster", team_id=1, weight=30, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Let's Go", team_id=1, weight=27, first_season=10, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="2016 Cadillac ATS-V R", team_id=1, weight=37, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="2018 Dodge Durango", team_id=1, weight=43, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1971 Plymouth GTX", team_id=1, weight=39, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="1970 Dodge Charger", team_id=1, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Donut Drifter (Grape Jelly)", team_id=3, weight=30, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Olds 442 W-30 Monster Truck", team_id=3, weight=37, first_season=10, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="DMC DeLorean", team_id=3, weight=30, first_season=10, event_appearances=7, champion=0, second=0, third=0),
    Vehicle(name="Mercedes AMG GT 63 S", team_id=3, weight=33, first_season=10, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Bot Wheels", team_id=3, weight=34, first_season=10, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1978 Subaru BRAT", team_id=3, weight=38, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Custom 2001 Acura Integra", team_id=3, weight=32, first_season=10, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="1970 Chevelle SS Wagon", team_id=3, weight=40, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1950 Chevy Suburban ", team_id=3, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1965 Ford Galaxie (Yellow)", team_id=3, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="K.I.T. Super Pursuit Mode", team_id=3, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Custom Small Block (Tropical)", team_id=4, weight=37, first_season=10, event_appearances=7, champion=1, second=0, third=0),
    Vehicle(name="Nissan Skyline 2000 (Gray)", team_id=4, weight=37, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="2009 Ford F-150", team_id=4, weight=47, first_season=10, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Retro Yellow", team_id=4, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="2016 Alfa Romeo Giulia", team_id=4, weight=35, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Lolux", team_id=4, weight=33, first_season=10, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1955 Chevy", team_id=4, weight=31, first_season=10, event_appearances=4, champion=0, second=0, third=0),
    Vehicle(name="1969 Chevelle Orange", team_id=4, weight=35, first_season=10, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="Nissan Leaf Nismo RC.02", team_id=4, weight=32, first_season=10, event_appearances=6, champion=0, second=0, third=1),
    Vehicle(name="Volkswagen Käfer Racer", team_id=4, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="Space Jam Van", team_id=5, weight=48, first_season=10, event_appearances=6, champion=0, second=0, third=0),
    Vehicle(name="1970 Ford Capri (Olive Green)", team_id=5, weight=34, first_season=10, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="Toyota Land Cruiser 80", team_id=5, weight=38, first_season=10, event_appearances=9, champion=0, second=0, third=0),
    Vehicle(name="1968 Shelby GT 500", team_id=5, weight=36, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Subaru SVX", team_id=5, weight=34, first_season=10, event_appearances=2, champion=0, second=0, third=0),
    Vehicle(name="Cockney Cab 2", team_id=5, weight=36, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1956 Ford-100", team_id=5, weight=42, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1966 Chevy Nova", team_id=5, weight=36, first_season=10, event_appearances=3, champion=0, second=0, third=0),
    Vehicle(name="1988 Chevy Monte Carlo", team_id=5, weight=40, first_season=10, event_appearances=1, champion=0, second=0, third=0),
    Vehicle(name="1969 Cougar Eliminator", team_id=5, first_season=10, event_appearances=4, champion=0, second=0, third=0),

    # Season
    Season(season_num=1),
    Season(season_num=2),
    Season(season_num=3),
    Season(season_num=4),
    Season(season_num=5),
    Season(season_num=6),
    Season(season_num=7),
    Season(season_num=8),
    Season(season_num=9),
    Season(season_num=10),

    # EventType
    EventType(name="Damon"),
    EventType(name="Long Launch"),
    EventType(name="Enduro"),
    EventType(name="Rowdy"),
    EventType(name="Spectacle"),
    EventType(name="Open-Trip"),
    EventType(name="Double Double"),
    EventType(name="Felix"),

    # Event
    # Season 1: Regular Season
    Event(season_num=1, event_num=1, type=1, name="Damon 15", date=date(2020, 6, 17), winner=5, team=1, champions_league=False),
    Event(season_num=1, event_num=2, type=2, name="Damon Long Launch 7", date=date(2020, 6, 17), winner=7, team=1, champions_league=False),
    Event(season_num=1, event_num=3, type=3, name="Enduro 34", date=date(2020, 6, 22), winner=8, team=1, champions_league=False),
    Event(season_num=1, event_num=4, type=4, name="Rowdy 4x6", date=date(2020, 6, 22), winner=8, team=1, champions_league=False),
    Event(season_num=1, event_num=5, type=2, name="Long Launch X", date=date(2020, 6, 27), winner=37, team=5, champions_league=False),
    Event(season_num=1, event_num=6, type=4, name="Rowdy 4x5", date=date(2020, 6, 27), winner=19, team=3, champions_league=False),
    Event(season_num=1, event_num=7, type=4, name="Rowdy Hop 4x5", date=date(2020, 6, 27), winner=16, team=3, champions_league=False),
    Event(season_num=1, event_num=8, type=3, name="Enduro EX4", date=date(2020, 7, 1), winner=27, team=4, champions_league=False),
    Event(season_num=1, event_num=9, type=2, name="Long Launch EX13", date=date(2020, 7, 2), winner=18, team=3, champions_league=False),
    Event(season_num=1, event_num=10, type=4, name="Rowdy Free 4x7.75", date=date(2020, 7, 6), winner=23, team=3, champions_league=False),
    Event(season_num=1, event_num=11, type=3, name="Enduro Dip ’n Rock 5", date=date(2020, 7, 10), winner=32, team=5, champions_league=False),
    Event(season_num=1, event_num=12, type=3, name="Enduro Pure", date=date(2020, 7, 10), winner=26, team=4, champions_league=False),
    Event(season_num=1, event_num=13, type=4, name="Rowdy Launch 7", date=date(2020, 7, 12), winner=3, team=1, champions_league=False),
    # Season 1: Champions League
    Event(season_num=1, event_num=14, type=5, name="Spectacle 12", date=date(2020, 7, 16), winner=16, team=3, champions_league=True),
    Event(season_num=1, event_num=15, type=2, name="Long Launch 3/4 EX", date=date(2020, 7, 16), winner=32, team=5, champions_league=True),
    Event(season_num=1, event_num=16, type=4, name="The Rowdy Hump, Flop & Skip", date=date(2020, 7, 20), winner=3, team=1, champions_league=True),
    Event(season_num=1, event_num=17, type=3, name="Enduro A.S.P. (Angle, Slant, Poop)", date=date(2020, 7, 24), winner=27, team=4, champions_league=True),
    Event(season_num=1, event_num=18, type=1, name="Damon 66", date=date(2020, 7, 24), winner=3, team=1, champions_league=True),
    # Season 2: Regular Season
    Event(season_num=2, event_num=1, type=4, name="Rowdy Flop 'n Slide", date=date(2020, 7, 16), winner=71, team=5, champions_league=False),
    Event(season_num=2, event_num=2, type=3, name="Enduro Hippity-Hop", date=date(2020, 7, 29), winner=61, team=4, champions_league=False),
    Event(season_num=2, event_num=3, type=2, name="Long Launch Reverso 12", date=date(2020, 7, 30), winner=18, team=3, champions_league=False),
    Event(season_num=2, event_num=4, type=4, name="Rowdy Plastic Ice", date=date(2020, 8, 3), winner=69, team=5, champions_league=False),
    Event(season_num=2, event_num=5, type=6, name="Trip-Open 3", date=date(2020, 8, 7), winner=35, team=5, champions_league=False),
    Event(season_num=2, event_num=6, type=3, name="Enduro Gap O’Ice", date=date(2020, 8, 9), winner=65, team=4, champions_league=False),
    Event(season_num=2, event_num=7, type=4, name="Rowdy Funnel-Trip", date=date(2020, 8, 12), winner=46, team=1, champions_league=False),
    Event(season_num=2, event_num=8, type=6, name="Open-Trip Cruise ’n Narrow", date=date(2020, 8, 17), winner=3, team=1, champions_league=False),
    Event(season_num=2, event_num=9, type=2, name="Long Launch Classic", date=date(2020, 8, 17), winner=73, team=5, champions_league=False),
    Event(season_num=2, event_num=10, type=6, name="Open-Trip Launch", date=date(2020, 8, 21), winner=25, team=4, champions_league=False),
    Event(season_num=2, event_num=11, type=4, name="Rowdy Hop Narrows", date=date(2020, 8, 21), winner=16, team=3, champions_league=False),
    Event(season_num=2, event_num=12, type=3, name="Enduro Combo 5", date=date(2020, 8, 22), winner=41, team=1, champions_league=False),
    # Season 2: Champions League
    Event(season_num=2, event_num=13, type=5, name="Spectacle 12", date=date(2020, 8, 22), winner=46, team=1, champions_league=True),
    Event(season_num=2, event_num=14, type=6, name="Open Trip Open", date=date(2020, 8, 26), winner=61, team=4, champions_league=True),
    Event(season_num=2, event_num=15, type=2, name="Traditional Long Launch", date=date(2020, 8, 26), winner=46, team=1, champions_league=True),
    Event(season_num=2, event_num=16, type=3, name="Enduro K.A.S.I.P. (Kitchen, Angle, Slant, Ice, Poop)", date=date(2020, 8, 27), winner=41, team=1, champions_league=True),
    Event(season_num=2, event_num=17, type=4, name="Rowdy 90 Double Funnel", date=date(2020, 8, 30), winner=3, team=1, champions_league=True),
    # Season 3: Regular Season
    Event(season_num=3, event_num=1, type=4, name="Rowdy Alley Open 6", date=date(2020, 8, 31), winner=8, team=1, champions_league=False),
    Event(season_num=3, event_num=2, type=6, name="Open Trip Dip 'n Fall", date=date(2020, 9, 3), winner=53, team=3, champions_league=False),
    Event(season_num=3, event_num=3, type=6, name="Open Trip Dozen Mayhem!!!", date=date(2020, 9, 3), winner=70, team=5, champions_league=False),
    Event(season_num=3, event_num=4, type=3, name="Enduro Banana Bend 5", date=date(2020, 9, 4), winner=71, team=5, champions_league=False),
    Event(season_num=3, event_num=5, type=2, name="Long Launch Candle Gap", date=date(2020, 9, 4), winner=18, team=3, champions_league=False),
    Event(season_num=3, event_num=6, type=4, name="Rowdy Icy Grass", date=date(2020, 9, 4), winner=64, team=4, champions_league=False),
    Event(season_num=3, event_num=7, type=3, name="Enduro Ice Cliff Drop", date=date(2020, 9, 10), winner=58, team=3, champions_league=False),
    Event(season_num=3, event_num=8, type=4, name="Rowdy 90 Open", date=date(2020, 9, 10), winner=42, team=1, champions_league=False),
    Event(season_num=3, event_num=9, type=6, name="Open Trip Double 90", date=date(2020, 9, 14), winner=43, team=1, champions_league=False),
    Event(season_num=3, event_num=10, type=1, name="Damon Double 16", date=date(2020, 9, 14), winner=3, team=1, champions_league=False),
    Event(season_num=3, event_num=11, type=2, name="Long Launch Gap 'n Slide", date=date(2020, 9, 16), winner=95, team=5, champions_league=False),
    Event(season_num=3, event_num=12, type=7, name="Double Double Ride", date=date(2020, 9, 16), winner=69, team=5, champions_league=False),
    # Season 3: Champions League
    Event(season_num=3, event_num=13, type=5, name="Spectacle 3x4 Lighty", date=date(2020, 9, 19), winner=42, team=1, champions_league=True),
    Event(season_num=3, event_num=14, type=4, name="Rowdy Lighty", date=date(2020, 9, 19), winner=42, team=1, champions_league=True),
    Event(season_num=3, event_num=15, type=2, name="Long Launch Wide 'n Free", date=date(2020, 9, 28), winner=64, team=4, champions_league=True),
    Event(season_num=3, event_num=16, type=3, name="Enduro 90° 7", date=date(2020, 10, 2), winner=43, team=1, champions_league=True),
    Event(season_num=3, event_num=17, type=4, name="Rowdy Classy Loch", date=date(2020, 10, 2), winner=42, team=1, champions_league=True),
    # Season 4: Regular Season
    Event(season_num=4, event_num=1, type=3, name="Enduro Lazy Horseshoe", date=date(2020, 10, 4), winner=115, team=3, champions_league=False),
    Event(season_num=4, event_num=2, type=4, name="Rowdy Rally D.T. 16", date=date(2020, 10, 7), winner=93, team=5, champions_league=False),
    Event(season_num=4, event_num=3, type=1, name="Damon D.T. 16", date=date(2020, 10, 7), winner=100, team=1, champions_league=False),
    Event(season_num=4, event_num=4, type=4, name="Rowdy Kinda Open", date=date(2020, 10, 11), winner=59, team=4, champions_league=False),
    Event(season_num=4, event_num=5, type=2, name="Long Launch Reverso SWS (South Wall Slide)", date=date(2020, 10, 12), winner=122, team=4, champions_league=False),
    Event(season_num=4, event_num=6, type=3, name="Enduro Round 'n Round Couch", date=date(2020, 10, 17), winner=35, team=5, champions_league=False),
    Event(season_num=4, event_num=7, type=4, name="Rowdy Wide Rally", date=date(2020, 10, 21), winner=129, team=5, champions_league=False),
    Event(season_num=4, event_num=8, type=2, name="Long Launch Snail Slide", date=date(2020, 10, 26), winner=135, team=5, champions_league=False),
    Event(season_num=4, event_num=9, type=1, name="Damon Freeway", date=date(2020, 10, 30), winner=16, team=3, champions_league=False),
    Event(season_num=4, event_num=10, type=7, name="Double Double Damon Freeway", date=date(2020, 10, 31), winner=61, team=4, champions_league=False),
    Event(season_num=4, event_num=11, type=3, name="Enduro Elbow Slide", date=date(2020, 11, 1), winner=88, team=4, champions_league=False),
    Event(season_num=4, event_num=12, type=4, name="Rowdy Little Hoppy", date=date(2020, 11, 8), winner=106, team=1, champions_league=False),
    # Season 4: Champions League
    Event(season_num=4, event_num=13, type=5, name="Spectacle Party in the Alley", date=date(2020, 11, 9), winner=61, team=4, champions_league=True),
    Event(season_num=4, event_num=14, type=2, name="Long Launch Baby Blanket", date=date(2020, 11, 13), winner=115, team=3, champions_league=True),
    Event(season_num=4, event_num=15, type=3, name="Enduro Loop de Force", date=date(2020, 11, 14), winner=115, team=3, champions_league=True),
    Event(season_num=4, event_num=16, type=4, name="Rowdy Sea of Green", date=date(2020, 11, 22), winner=106, team=1, champions_league=True),
    Event(season_num=4, event_num=17, type=7, name="Double Double Green Supreme", date=date(2020, 11, 23), winner=106, team=1, champions_league=True),
    # Season 5: Regular Season
    Event(season_num=5, event_num=1, type=7, name="Double Double Hard Stoppin'", date=date(2020, 11, 26), winner=107, team=1, champions_league=False),
    Event(season_num=5, event_num=2, type=1, name="Damon Hot Doggy Cross-Over", date=date(2020, 11, 27), winner=106, team=1, champions_league=False),
    Event(season_num=5, event_num=3, type=4, name="Rowdy Banana Split", date=date(2020, 11, 27), winner=133, team=5, champions_league=False),
    Event(season_num=5, event_num=4, type=3, name="Enduro Big Swing Turn", date=date(2020, 11, 28), winner=165, team=4, champions_league=False),
    Event(season_num=5, event_num=5, type=2, name="Long Launch Big Red", date=date(2020, 12, 1), winner=162, team=4, champions_league=False),
    Event(season_num=5, event_num=6, type=1, name="Damon Slightly Slanted Horseshoe", date=date(2020, 12, 3), winner=118, team=4, champions_league=False),
    Event(season_num=5, event_num=7, type=7, name="Double Double Criss-Crossin'", date=date(2020, 12, 7), winner=143, team=1, champions_league=False),
    Event(season_num=5, event_num=8, type=3, name="Enduro Horse Potty", date=date(2020, 12, 12), winner=167, team=5, champions_league=False),
    Event(season_num=5, event_num=9, type=4, name="Rowdy Split Duo", date=date(2020, 12, 12), winner=168, team=1, champions_league=False),
    Event(season_num=5, event_num=10, type=2, name="Long Launch Big Blue Reverso", date=date(2020, 12, 13), winner=126, team=4, champions_league=False),
    Event(season_num=5, event_num=11, type=1, name="Damon Back 'n Forth", date=date(2020, 12, 21), winner=16, team=3, champions_league=False),
    Event(season_num=5, event_num=12, type=6, name="Open-Trip Lego Head Hop", date=date(2020, 12, 22), winner=111, team=3, champions_league=False),
    # Season 5: Champions League
    Event(season_num=5, event_num=13, type=5, name="Spectacle 4x3 Boxing Green", date=date(2020, 12, 26), winner=133, team=5, champions_league=True),
    Event(season_num=5, event_num=14, type=4, name="Rowdy Pointy Hop", date=date(2020, 12, 26), winner=106, team=1, champions_league=True),
    Event(season_num=5, event_num=15, type=2, name="Long Launch BBAR (Big Blue Air Reverso)", date=date(2020, 12, 31), winner=107, team=1, champions_league=True),
    Event(season_num=5, event_num=16, type=3, name="Enduro Downhill Couch", date=date(2021, 1, 8), winner=165, team=4, champions_league=True),
    Event(season_num=5, event_num=17, type=7, name="Double Double Carpet Scramble", date=date(2021, 1, 9), winner=168, team=5, champions_league=True),
    # Season 6: Regular Season
    Event(season_num=6, event_num=1, type=4, name="Rowdy Scoot", date=date(2021, 1, 10), winner=189, team=3, champions_league=False),
    Event(season_num=6, event_num=2, type=2, name="Long Launch Back-Slide", date=date(2021, 1, 18), winner=182, team=1, champions_league=False),
    Event(season_num=6, event_num=3, type=1, name="Damon Long Draggin'", date=date(2021, 1, 22), winner=106, team=1, champions_league=False),
    Event(season_num=6, event_num=4, type=7, name="Double Double Fast 'n Free", date=date(2021, 1, 22), winner=100, team=1, champions_league=False),
    Event(season_num=6, event_num=5, type=4, name="Rowdy Under-Turn", date=date(2021, 1, 23), winner=185, team=3, champions_league=False),
    Event(season_num=6, event_num=6, type=3, name="Upstairs Couch Enduro", date=date(2021, 2, 5), winner=193, team=4, champions_league=False),
    Event(season_num=6, event_num=7, type=1, name="Damon Upstairs Drive", date=date(2021, 2, 10), winner=49, team=3, champions_league=False),
    Event(season_num=6, event_num=8, type=7, name="Double Double Upstairs Triangle", date=date(2021, 2, 11), winner=103, team=1, champions_league=False),
    Event(season_num=6, event_num=9, type=2, name="Long Launch Upstairs San Reverso", date=date(2021, 2, 14), winner=200, team=5, champions_league=False),
    Event(season_num=6, event_num=10, type=4, name="Being Rowdy Upstairs", date=date(2021, 2, 15), winner=132, team=5, champions_league=False),
    Event(season_num=6, event_num=11, type=1, name="Damon Triple Curve", date=date(2021, 2, 16), winner=188, team=3, champions_league=False),
    Event(season_num=6, event_num=12, type=7, name="Double Double Triple Curve", date=date(2021, 2, 16), winner=64, team=4, champions_league=False),
    # Season 6: Champions League
    Event(season_num=6, event_num=13, type=5, name="Spectacle Carpet Run", date=date(2021, 2, 16), winner=182, team=1, champions_league=True),
    Event(season_num=6, event_num=14, type=3, name="Enduro Hold On Tight 8", date=date(2021, 2, 21), winner=103, team=1, champions_league=True),
    Event(season_num=6, event_num=15, type=1, name="Damon Almost Squared", date=date(2021, 2, 25), winner=189, team=3, champions_league=True),
    Event(season_num=6, event_num=16, type=2, name="Long Launch Skinny Pure", date=date(2021, 2, 25), winner=182, team=1, champions_league=True),
    Event(season_num=6, event_num=17, type=4, name="Rowdy Classic Landing", date=date(2021, 2, 26), winner=200, team=5, champions_league=True),
    # Season 7: Regular Season
    Event(season_num=7, event_num=1, type=7, name="Bedroom Double Double 180", date=date(2021, 3, 20), winner=257, team=5, champions_league=False),
    Event(season_num=7, event_num=2, type=1, name="Damon 180 Bedroom", date=date(2021, 3, 20), winner=230, team=3, champions_league=False),
    Event(season_num=7, event_num=3, type=3, name="Enduro Jump 'n Run", date=date(2021, 3, 25), winner=224, team=3, champions_league=False),
    Event(season_num=7, event_num=4, type=4, name="Rowdy Cardboard Rollin'", date=date(2021, 3, 26), winner=242, team=4, champions_league=False),
    Event(season_num=7, event_num=5, type=7, name="Double Double Cardboard 180", date=date(2021, 3, 26), winner=208, team=1, champions_league=False),
    Event(season_num=7, event_num=6, type=1, name="Damon 270 Bedroom", date=date(2021, 4, 24), winner=245, team=4, champions_league=False),
    Event(season_num=7, event_num=7, type=7, name="Double Double 270 Bedroom", date=date(2021, 4, 24), winner=244, team=4, champions_league=False),
    Event(season_num=7, event_num=8, type=4, name="Rowdy Classic Cardboard Lanes", date=date(2021, 5, 22), winner=237, team=4, champions_league=False),
    Event(season_num=7, event_num=9, type=4, name="Rowdy Cardboard Extended Lanes", date=date(2021, 5, 22), winner=231, team=3, champions_league=False),
    Event(season_num=7, event_num=10, type=2, name="Long Launch Straight Slidin'", date=date(2021, 5, 29), winner=211, team=1, champions_league=False),
    Event(season_num=7, event_num=11, type=4, name="Rowdy Heart", date=date(2021, 5, 30), winner=258, team=5, champions_league=False),
    Event(season_num=7, event_num=12, type=1, name="Damon Heart", date=date(2021, 5, 30), winner=225, team=3, champions_league=False),
    # Season 7: Champions League
    Event(season_num=7, event_num=13, type=5, name="Split Spectacle Triple-Double Couch Surfing", date=date(2021, 6, 9), winner=242, team=4, champions_league=True),
    Event(season_num=7, event_num=14, type=1, name="Damon 180 Anniversary Hop", date=date(2021, 6, 17), winner=225, team=3, champions_league=True),
    Event(season_num=7, event_num=15, type=4, name="Rowdy USA", date=date(2021, 7, 3), winner=244, team=4, champions_league=True),
    Event(season_num=7, event_num=16, type=7, name="Double Double USA", date=date(2021, 7, 3), winner=258, team=5, champions_league=True),
    Event(season_num=7, event_num=17, type=3, name="Toilet Hybrid Long Launch Enduro", date=date(2021, 7, 14), winner=244, team=4, champions_league=True),
    # Season 8: Regular Season
    Event(season_num=8, event_num=1, type=7, name="Double Double Crosstown Couch", date=date(2021, 7, 15), winner=287, team=4, champions_league=False),
    Event(season_num=8, event_num=2, type=1, name="Damon Crosstown Couch", date=date(2021, 7, 15), winner=274, team=3, champions_league=False),
    Event(season_num=8, event_num=3, type=1, name="Damon Motel 6", date=date(2021, 7, 18), winner=273, team=3, champions_league=False),
    Event(season_num=8, event_num=4, type=4, name="Rowdy Rolling Hop", date=date(2021, 8, 5), winner=300, team=5, champions_league=False),
    Event(season_num=8, event_num=5, type=7, name="Double Double Short Turn", date=date(2021, 8, 5), winner=291, team=4, champions_league=False),
    Event(season_num=8, event_num=6, type=1, name="Damon Hallway Dragin'", date=date(2021, 8, 6), winner=286, team=4, champions_league=False),
    Event(season_num=8, event_num=7, type=7, name="Super Double Double", date=date(2021, 8, 7), winner=225, team=3, champions_league=False),
    Event(season_num=8, event_num=8, type=3, name="Enduro Launch and Loop Raceway", date=date(2021, 10, 27), winner=280, team=3, champions_league=False),
    Event(season_num=8, event_num=9, type=1, name="Damon CP Classic I", date=date(2021, 11, 2), winner=297, team=4, champions_league=False),
    Event(season_num=8, event_num=10, type=7, name="Double Double Big 'ol S", date=date(2021, 11, 13), winner=299, team=5, champions_league=False),
    Event(season_num=8, event_num=11, type=4, name="Rowdy Candy Cane (x2) Lane", date=date(2021, 11, 23), winner=262, team=1, champions_league=False),
    Event(season_num=8, event_num=12, type=2, name="Long Launch Couch Surfing", date=date(2021, 12, 23), winner=277, team=3, champions_league=False),
    # Season 8: Champions League
    Event(season_num=8, event_num=13, type=5, name="Spectacle 90° Delectable", date=date(2021, 12, 29), winner=297, team=4, champions_league=True),
    Event(season_num=8, event_num=14, type=1, name="Damon Crossover Croissant Deluxe", date=date(2021, 1, 14), winner=225, team=3, champions_league=True),
    Event(season_num=8, event_num=15, type=7, name="Double Double Deluxe Deluxe", date=date(2021, 1, 14), winner=297, team=4, champions_league=True),
    Event(season_num=8, event_num=16, type=8, name="Felix Sour 135", date=date(2021, 1, 16), winner=286, team=4, champions_league=True),
    Event(season_num=8, event_num=17, type=4, name="Rowdy Wood at 45°", date=date(2021, 1, 26), winner=273, team=3, champions_league=True),
    # Season 9: Regular Season
    Event(season_num=9, event_num=1, type=1, name="Damon Outerside Heart", date=date(2022, 2, 9), winner=42, team=1, champions_league=False),
    Event(season_num=9, event_num=2, type=4, name="Rowdy Pink Blanket", date=date(2022, 2, 9), winner=317, team=1, champions_league=False),
    Event(season_num=9, event_num=3, type=7, name="Double Double Just About Right", date=date(2022, 2, 16), winner=312, team=1, champions_league=False),
    Event(season_num=9, event_num=4, type=1, name="Damon Almost Right", date=date(2022, 2, 16), winner=297, team=4, champions_league=False),
    Event(season_num=9, event_num=5, type=8, name="Felix Sit Back and Relax", date=date(2022, 2, 20), winner=103, team=1, champions_league=False),
    Event(season_num=9, event_num=6, type=7, name="Double Double Banking Right", date=date(2022, 2, 22), winner=343, team=4, champions_league=False),
    Event(season_num=9, event_num=7, type=1, name="Damon Freeway Banking", date=date(2022, 2, 22), winner=337, team=4, champions_league=False),
    Event(season_num=9, event_num=8, type=2, name="Long Launch Horse Swoop", date=date(2022, 2, 26), winner=318, team=1, champions_league=False),
    Event(season_num=9, event_num=9, type=4, name="Rowdy Ridge Towel", date=date(2022, 3, 5), winner=225, team=3, champions_league=False),
    Event(season_num=9, event_num=10, type=7, name="Double Double Baby Doll Hop", date=date(2022, 3, 5), winner=340, team=4, champions_league=False),
    Event(season_num=9, event_num=11, type=4, name="Rowdy Kablooey Classic", date=date(2022, 3, 20), winner=314, team=1, champions_league=False),
    Event(season_num=9, event_num=12, type=1, name="Damon Kablooey Classic", date=date(2022, 3, 20), winner=321, team=1, champions_league=False),
    # Season 9: Champions League
    Event(season_num=9, event_num=13, type=5, name="Split Spectacle Incomplete 8", date=date(2022, 4, 1), winner=103, team=1, champions_league=True),
    Event(season_num=9, event_num=14, type=1, name="Damon Green Hot Sauce", date=date(2022, 4, 1), winner=312, team=1, champions_league=True),
    Event(season_num=9, event_num=15, type=3, name="Enduro Real Stuff", date=date(2022, 4, 2), winner=297, team=4, champions_league=True),
    Event(season_num=9, event_num=16, type=4, name="Rowdy Long Long", date=date(2022, 4, 8), winner=321, team=1, champions_league=True),
    Event(season_num=9, event_num=17, type=1, name="Damon Double-Cross Easter Honk!", date=date(2022, 4, 17), winner=42, team=1, champions_league=True),
    # Season 10: Regular Season
    Event(season_num=10, event_num=1, type=4, name="Rowdy Classic Heart", date=date(2022, 4, 29), winner=357, team=1, champions_league=False),
    Event(season_num=10, event_num=2, type=7, name="Double Double Inside Classic Heart", date=date(2022, 4, 29), winner=388, team=5, champions_league=False),
    Event(season_num=10, event_num=3, type=8, name="Felix Relaxciting 2", date=date(2022, 4, 30), winner=369, team=3, champions_league=False),
    Event(season_num=10, event_num=4, type=1, name="Damon Classic Summer Return", date=date(2022, 8, 2), winner=386, team=4, champions_league=False),
    Event(season_num=10, event_num=5, type=2, name="Long Launch Aerobics", date=date(2022, 8, 3), winner=257, team=5, champions_league=False),
    Event(season_num=10, event_num=6, type=4, name="Rowdy Floppy Heart", date=date(2022, 8, 11), winner=286, team=4, champions_league=False),
    Event(season_num=10, event_num=7, type=7, name="Double Double Li'l Smooth Hop", date=date(2022, 8, 11), winner=378, team=4, champions_league=False),
    Event(season_num=10, event_num=8, type=4, name="Rowdy Carpet Runner", date=date(2022, 8, 18), winner=297, team=4, champions_league=False),
    Event(season_num=10, event_num=9, type=7, name="Double Double Carpet Runner", date=date(2022, 8, 18), winner=390, team=5, champions_league=False),
    Event(season_num=10, event_num=10, type=3, name="Enduro Big Vehicles and Books", date=date(2022, 8, 22), winner=373, team=3, champions_league=False),
    Event(season_num=10, event_num=11, type=1, name="Damon City Rug", date=date(2022, 9, 23), winner=42, team=1, champions_league=False),
    Event(season_num=10, event_num=12, type=1, name="Damon Interchange Rug City", date=date(2022, 10, 2), winner=15, team=3, champions_league=False),
    # Season 9: Champions League
    Event(season_num=10, event_num=13, type=5, name="Split Spectacle Culvert", date=date(2022, 10, 30), winner=42, team=1, champions_league=True),
    Event(season_num=10, event_num=14, type=4, name="Rowdy Hardwood Freeway", date=date(2022, 11, 5), winner=378, team=4, champions_league=True),
    Event(season_num=10, event_num=15, type=7, name="Double Double Free on the Highway", date=date(2022, 11, 5), winner=378, team=4, champions_league=True),
    Event(season_num=10, event_num=16, type=3, name="Enduro Speaker Box 13", date=date(2022, 12, 11), winner=386, team=4, champions_league=True),
    Event(season_num=10, event_num=17, type=1, name="Damon 90° + 45° = Fun!", date=date(2022, 12, 12), winner=378, team=4, champions_league=True),

    # ChampionsLeagueResult
    # Season 1
    ChampionsLeagueResult(season_num=1, place=1, vehicle=3, team=1, points=47),
    ChampionsLeagueResult(season_num=1, place=2, vehicle=16, team=3, points=43),
    ChampionsLeagueResult(season_num=1, place=3, vehicle=5, team=1, points=40),
    ChampionsLeagueResult(season_num=1, place=4, vehicle=37, team=5, points=39),
    ChampionsLeagueResult(season_num=1, place=5, vehicle=26, team=4, points=38),
    ChampionsLeagueResult(season_num=1, place=6, vehicle=23, team=4, points=34),
    ChampionsLeagueResult(season_num=1, place=7, vehicle=32, team=5, points=33),
    ChampionsLeagueResult(season_num=1, place=8, vehicle=8, team=1, points=32),
    ChampionsLeagueResult(season_num=1, place=9, vehicle=27, team=4, points=28),
    ChampionsLeagueResult(season_num=1, place=10, vehicle=18, team=3, points=24),
    ChampionsLeagueResult(season_num=1, place=11, vehicle=7, team=1, points=17),
    ChampionsLeagueResult(season_num=1, place=12, vehicle=19, team=3, points=15),
    # Season 2
    ChampionsLeagueResult(season_num=2, place=1, vehicle=46, team=1, points=40),
    ChampionsLeagueResult(season_num=2, place=2, vehicle=61, team=4, points=39),
    ChampionsLeagueResult(season_num=2, place=3, vehicle=3, team=1, points=37),
    ChampionsLeagueResult(season_num=2, place=4, vehicle=41, team=1, points=35),
    ChampionsLeagueResult(season_num=2, place=5, vehicle=71, team=5, points=35),
    ChampionsLeagueResult(season_num=2, place=6, vehicle=16, team=3, points=35),
    ChampionsLeagueResult(season_num=2, place=7, vehicle=25, team=4, points=33),
    ChampionsLeagueResult(season_num=2, place=8, vehicle=69, team=5, points=32),
    ChampionsLeagueResult(season_num=2, place=9, vehicle=35, team=5, points=30),
    ChampionsLeagueResult(season_num=2, place=10, vehicle=73, team=5, points=29),
    ChampionsLeagueResult(season_num=2, place=11, vehicle=18, team=3, points=29),
    ChampionsLeagueResult(season_num=2, place=12, vehicle=65, team=4, points=16),
    # Season 3
    ChampionsLeagueResult(season_num=3, place=1, vehicle=42, team=1, points=55),
    ChampionsLeagueResult(season_num=3, place=2, vehicle=43, team=1, points=45),
    ChampionsLeagueResult(season_num=3, place=3, vehicle=71, team=5, points=40),
    ChampionsLeagueResult(season_num=3, place=4, vehicle=64, team=4, points=39),
    ChampionsLeagueResult(season_num=3, place=5, vehicle=3, team=1, points=36),
    ChampionsLeagueResult(season_num=3, place=6, vehicle=95, team=5, points=34),
    ChampionsLeagueResult(season_num=3, place=7, vehicle=8, team=1, points=32),
    ChampionsLeagueResult(season_num=3, place=8, vehicle=58, team=3, points=31),
    ChampionsLeagueResult(season_num=3, place=9, vehicle=70, team=5, points=26),
    ChampionsLeagueResult(season_num=3, place=10, vehicle=69, team=5, points=18),
    ChampionsLeagueResult(season_num=3, place=11, vehicle=18, team=3, points=17),
    ChampionsLeagueResult(season_num=3, place=12, vehicle=53, team=3, points=17),
    # Season 4
    ChampionsLeagueResult(season_num=4, place=1, vehicle=106, team=1, points=41),
    ChampionsLeagueResult(season_num=4, place=2, vehicle=100, team=1, points=40),
    ChampionsLeagueResult(season_num=4, place=3, vehicle=35, team=5, points=38),
    ChampionsLeagueResult(season_num=4, place=4, vehicle=122, team=4, points=38),
    ChampionsLeagueResult(season_num=4, place=5, vehicle=115, team=3, points=37),
    ChampionsLeagueResult(season_num=4, place=6, vehicle=93, team=5, points=35),
    ChampionsLeagueResult(season_num=4, place=7, vehicle=61, team=4, points=33),
    ChampionsLeagueResult(season_num=4, place=8, vehicle=59, team=4, points=32),
    ChampionsLeagueResult(season_num=4, place=9, vehicle=88, team=4, points=28),
    ChampionsLeagueResult(season_num=4, place=10, vehicle=16, team=3, points=23),
    ChampionsLeagueResult(season_num=4, place=11, vehicle=129, team=5, points=23),
    ChampionsLeagueResult(season_num=4, place=12, vehicle=135, team=5, points=22),
    # Season 5
    ChampionsLeagueResult(season_num=5, place=1, vehicle=168, team=5, points=44),
    ChampionsLeagueResult(season_num=5, place=2, vehicle=111, team=3, points=40),
    ChampionsLeagueResult(season_num=5, place=3, vehicle=165, team=4, points=38),
    ChampionsLeagueResult(season_num=5, place=4, vehicle=133, team=5, points=36),
    ChampionsLeagueResult(season_num=5, place=5, vehicle=16, team=3, points=35),
    ChampionsLeagueResult(season_num=5, place=6, vehicle=106, team=1, points=33),
    ChampionsLeagueResult(season_num=5, place=7, vehicle=143, team=1, points=33),
    ChampionsLeagueResult(season_num=5, place=8, vehicle=107, team=1, points=31),
    ChampionsLeagueResult(season_num=5, place=9, vehicle=167, team=5, points=29),
    ChampionsLeagueResult(season_num=5, place=10, vehicle=118, team=4, points=26),
    ChampionsLeagueResult(season_num=5, place=11, vehicle=126, team=4, points=23),
    ChampionsLeagueResult(season_num=5, place=12, vehicle=162, team=4, points=22),
    # Season 6
    ChampionsLeagueResult(season_num=6, place=1, vehicle=103, team=1, points=52),
    ChampionsLeagueResult(season_num=6, place=2, vehicle=193, team=4, points=40),
    ChampionsLeagueResult(season_num=6, place=3, vehicle=200, team=5, points=39),
    ChampionsLeagueResult(season_num=6, place=4, vehicle=188, team=3, points=37),
    ChampionsLeagueResult(season_num=6, place=5, vehicle=189, team=3, points=35),
    ChampionsLeagueResult(season_num=6, place=6, vehicle=106, team=1, points=35),
    ChampionsLeagueResult(season_num=6, place=7, vehicle=182, team=1, points=31),
    ChampionsLeagueResult(season_num=6, place=8, vehicle=64, team=4, points=30),
    ChampionsLeagueResult(season_num=6, place=9, vehicle=100, team=1, points=29),
    ChampionsLeagueResult(season_num=6, place=10, vehicle=49, team=3, points=26),
    ChampionsLeagueResult(season_num=6, place=11, vehicle=132, team=5, points=23),
    ChampionsLeagueResult(season_num=6, place=12, vehicle=185, team=3, points=13),
    # Season 7
    ChampionsLeagueResult(season_num=7, place=1, vehicle=225, team=3, points=49),
    ChampionsLeagueResult(season_num=7, place=2, vehicle=244, team=4, points=47),
    ChampionsLeagueResult(season_num=7, place=3, vehicle=242, team=4, points=40),
    ChampionsLeagueResult(season_num=7, place=4, vehicle=258, team=5, points=37),
    ChampionsLeagueResult(season_num=7, place=5, vehicle=230, team=3, points=36),
    ChampionsLeagueResult(season_num=7, place=6, vehicle=257, team=5, points=35),
    ChampionsLeagueResult(season_num=7, place=7, vehicle=231, team=3, points=31),
    ChampionsLeagueResult(season_num=7, place=8, vehicle=245, team=4, points=30),
    ChampionsLeagueResult(season_num=7, place=9, vehicle=211, team=1, points=30),
    ChampionsLeagueResult(season_num=7, place=10, vehicle=237, team=4, points=19),
    ChampionsLeagueResult(season_num=7, place=11, vehicle=224, team=3, points=19),
    ChampionsLeagueResult(season_num=7, place=12, vehicle=208, team=1, points=17),
    # Season 8
    ChampionsLeagueResult(season_num=8, place=1, vehicle=297, team=4, points=47),
    ChampionsLeagueResult(season_num=8, place=2, vehicle=286, team=4, points=47),
    ChampionsLeagueResult(season_num=8, place=3, vehicle=225, team=3, points=45),
    ChampionsLeagueResult(season_num=8, place=4, vehicle=287, team=4, points=43),
    ChampionsLeagueResult(season_num=8, place=5, vehicle=273, team=3, points=42),
    ChampionsLeagueResult(season_num=8, place=6, vehicle=291, team=4, points=36),
    ChampionsLeagueResult(season_num=8, place=7, vehicle=277, team=3, points=35),
    ChampionsLeagueResult(season_num=8, place=8, vehicle=274, team=3, points=35),
    ChampionsLeagueResult(season_num=8, place=9, vehicle=262, team=1, points=28),
    ChampionsLeagueResult(season_num=8, place=10, vehicle=300, team=5, points=16),
    ChampionsLeagueResult(season_num=8, place=11, vehicle=299, team=5, points=11),
    ChampionsLeagueResult(season_num=8, place=12, vehicle=280, team=3, points=6),
    # Season 9
    ChampionsLeagueResult(season_num=9, place=1, vehicle=42, team=1, points=48),
    ChampionsLeagueResult(season_num=9, place=2, vehicle=103, team=1, points=44),
    ChampionsLeagueResult(season_num=9, place=3, vehicle=312, team=1, points=42),
    ChampionsLeagueResult(season_num=9, place=4, vehicle=321, team=1, points=36),
    ChampionsLeagueResult(season_num=9, place=5, vehicle=337, team=4, points=34),
    ChampionsLeagueResult(season_num=9, place=6, vehicle=297, team=4, points=33),
    ChampionsLeagueResult(season_num=9, place=7, vehicle=317, team=1, points=32),
    ChampionsLeagueResult(season_num=9, place=8, vehicle=225, team=3, points=31),
    ChampionsLeagueResult(season_num=9, place=9, vehicle=343, team=4, points=26),
    ChampionsLeagueResult(season_num=9, place=10, vehicle=314, team=1, points=26),
    ChampionsLeagueResult(season_num=9, place=11, vehicle=318, team=1, points=16),
    ChampionsLeagueResult(season_num=9, place=12, vehicle=340, team=4, points=15),
    # Season 10
    ChampionsLeagueResult(season_num=10, place=1, vehicle=378, team=4, points=50),
    ChampionsLeagueResult(season_num=10, place=2, vehicle=42, team=1, points=50),
    ChampionsLeagueResult(season_num=10, place=3, vehicle=386, team=4, points=46),
    ChampionsLeagueResult(season_num=10, place=4, vehicle=373, team=3, points=37),
    ChampionsLeagueResult(season_num=10, place=5, vehicle=16, team=3, points=36),
    ChampionsLeagueResult(season_num=10, place=6, vehicle=286, team=4, points=36),
    ChampionsLeagueResult(season_num=10, place=7, vehicle=257, team=5, points=31),
    ChampionsLeagueResult(season_num=10, place=8, vehicle=388, team=5, points=28),
    ChampionsLeagueResult(season_num=10, place=9, vehicle=297, team=4, points=26),
    ChampionsLeagueResult(season_num=10, place=10, vehicle=357, team=1, points=20),
    ChampionsLeagueResult(season_num=10, place=11, vehicle=369, team=3, points=16),
    ChampionsLeagueResult(season_num=10, place=12, vehicle=390, team=5, points=14)
]

# session.add_all(data)
# session.commit()
# session.close()
# engine.dispose()
